package com.doston.enumeration;

public enum UserState {
    REGISTER,
    LOGIN,
    HOME,
    SEARCH,
    SEARCH_USERNAME,
    ADD_POST,
    ACCOUNT,
    NOTIFICATION,
    COMMENTS,
    POSTS,
    POST_COMMENTS,
    SAVED_POST_COMMENTS,
    FOLLOWERS,
    FOLLOWINGS,
    CHATS,
    CHAT,
    EDIT_PROFILE,
    PICTURE,
    NAME,
    USERNAME,
    BIO,
    BIRTHDATE,
    LINK,
    GENDER,
    SETTINGS,
    EMAIL,
    PASSWORD,
    LANGUAGE,
    SAVED_POSTS,

    HOST_ACCOUNT,
    HOST_POSTS,
    HOST_FOLLOWERS,
    HOST_FOLLOWINGS,
    HOST_CHAT,
    HOST_COMMENTS
}
